version: 2

jobs:
  test:
    docker: &BUILDIMAGE
      - image: jenkinsrise/cci-v2-docker-java8-gcloud:0.0.1
    working_directory: ~/cors-filter
    steps:
      - checkout
      - run: mvn test

  deploy:
    docker: *BUILDIMAGE
    working_directory: ~/cors-filter
    steps:
      - checkout
      - run: git config --global user.name $JENKINS_USERNAME
      - run: git config --global user.email $JENKINS_EMAIL
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run: cp private-keys/mvn-repo/mvn-repo-deploy-key* ~/.ssh/
      - run: cat ~/.ssh/mvn-repo-deploy-key.pub | tee -a ~/.ssh/authorized_keys
      - run: mvn deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
